site_name: Zettlr Docs
site_url: https://docs.zettlr.com/ja
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Zettlrを最大限活用するために必要となる、あらゆる情報を提供するドキュメンテーションです。
site_author: Hendrik Erz
copyright: "&copy; 2017-2020 by Zettlr"
docs_dir: ../docs/ja
site_dir: ../build/ja
edit_uri: edit/master/docs/ja
extra_css:
  - assets/app.css
nav:
  - ようこそ: index.md
  - 最初のステップ:
    - セットアップ: install.md
    - ポータブル版: portable.md
    - LaTeXのインストール: installing-latex.md
    - 最初の一歩: get-started.md
    - ご協力ください: get-involved.md
    - よくある質問: faq.md
    - トラブルシューティング: troubleshooting.md
  - 概念:
    - ファイル管理: concepts/workspaces.md
    - コンテキスト: concepts/context.md
    - WYSIWYM: concepts/wysiwym.md
  - 主要機能:
    - エディタ: core/editor.md
    - ドキュメントタブ: core/tabs.md
    - ファイルマネージャ: core/file-manager.md
    - アセットマネージャ: core/assets-manager.md
    - デフォルトファイル: core/defaults-files.md
    - カスタムCSS: core/custom-css.md
    - スニペット: core/snippets.md
    - オートコレクトとマジッククォート: core/autocorrect.md
    - 検索: core/search.md
    - インポート: core/import.md
    - エクスポート: core/export.md
    - テーブル編集: core/tables.md
    - ローカライゼーション: core/localisation.md
    - サイドバー: core/sidebar.md
    - YAML Frontmatter: core/yaml-frontmatter.md
    - 印刷とプレビュー: core/print-preview.md
    - 数式: core/math.md
  - 学術ツール:
    - 参考文献: academic/citations.md
    - プロジェクト: academic/projects.md
    - プレゼンテーション: academic/presentations.md
    - ポモドーロタイマー: academic/pomodoro.md
    - 可読性: academic/readability.md
    - Zettelkastenメソッド: academic/zkn-method.md
    - カスタムテンプレート: academic/custom-templates.md
  - 参考資料:
    - キーボードショートカット: reference/keyboard-shortcuts.md
    - Markdownの基本: reference/markdown-basics.md
    - 設定: reference/settings.md
    - スペルチェック: reference/spell-checking.md
theme:
  name: readthedocs
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search:
      lang: jp
