site_name: Manual do Usuário do Zettlr
site_url: https://docs.zettlr.com/pt
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Nossa documentação abrangente fornece tudo o que você precisa saber sobre como
    aproveitar ao máximo o Zettlr.
site_author: Hendrik Erz
copyright: "&copy; 2017-2026 by Zettlr"
docs_dir: ../docs/pt
site_dir: ../build/pt
edit_uri: edit/master/docs/pt
extra_css:
  - assets/app.css
nav:
  - Início: index.md
  - Começando:
    - Configuração: getting-started/setup.md
    - Migrando para um novo computador: getting-started/migrating.md
    - Instalando LaTeX: getting-started/installing-latex.md
    - Uma nota sobre segurança: getting-started/a-note-on-security.md
    - Participe: getting-started/get-involved.md
    - Solução de problemas: getting-started/troubleshooting.md
    - FAQ: reference/faq.md
  - Primeiros usuários:
    - Primeiros passos: first-time-users/first-steps.md
    - Espaços de trabalho: first-time-users/workspaces.md
    - Criando arquivos e pastas: first-time-users/creating-files-and-folders.md
    - Escrevendo Markdown: first-time-users/writing-markdown.md
    - Migrando do Word: first-time-users/import.md
    - Exportando arquivos: first-time-users/exporting-files.md
  - Gerenciador de arquivos:
    - Gerenciador de arquivos: file-manager/index.md
    - Espaços de trabalho e arquivos raiz: file-manager/workspaces-root-files.md
    - Escolhendo quais arquivos mostrar: file-manager/choosing-files.md
    - Aparência (modos): file-manager/appearance.md
    - Lista de arquivos: file-manager/file-list.md
    - Propriedades: file-manager/properties.md
    - Filtragem: file-manager/filtering.md
    - Pesquisa global: file-manager/search.md
    - Projetos: file-manager/projects.md
  - Exibição dividida:
    - Exibição dividida: split-view/index.md
    - Barra de abas de documentos: split-view/document-tab-bar.md
    - Editor Markdown: split-view/markdown-editor.md
    - Editor de código: split-view/code-editor.md
    - Visualizador de imagens: split-view/image-viewer.md
    - Visualizador de PDF: split-view/pdf-viewer.md
  - Barra lateral:
    - Barra lateral: sidebar/index.md
    - Sumário: sidebar/table-of-contents.md
    - Referências: sidebar/bibliography.md
    - Arquivos relacionados: sidebar/related-files.md
    - Outros arquivos: sidebar/other-files.md
  - Editor Markdown:
    - Editor Markdown: editor/index.md
    - Compêndio Markdown: editor/markdown-compendium.md
    - Aparência: editor/appearance.md
    - Pesquisa: editor/search.md
    - Autocompletar: editor/autocomplete.md
    - Notas de rodapé: editor/footnotes.md
    - Citações: editor/citations.md
    - Trabalhando com comentários: editor/comments.md
    - Barra de status: editor/statusbar.md
    - Editor de tabelas: editor/tables.md
    - Transformações de texto: editor/text-transforms.md
    - Trechos: editor/snippets.md
    - YAML Front Matter: editor/yaml-frontmatter.md
  - Idioma e estilo:
    - Idioma e estilo: language-style/index.md
    - Verificação ortográfica: language-style/spellchecking.md
    - LanguageTool: language-style/languagetool.md
    - Sintaxe Markdown: language-style/syntax.md
    - Autocorreção e MagicQuotes: language-style/autocorrect.md
    - Legibilidade: language-style/readability.md
  - Exportação:
    - Exportação: export/index.md
    - Fluxo de trabalho: export/workflow.md
    - Arquivos de padrões (perfis): export/defaults-files.md
    - Selecionando o motor PDF: export/pdf-engine.md
    - Gerenciador de ativos: export/assets-manager.md
    - Modelos personalizados: export/custom-templates.md
    - Comandos personalizados: export/custom-commands.md
    - Imprimir e visualizar: export/print-preview.md
    - Filtros Lua: export/lua-filters.md
  - Científico e técnico:
    - Científico e técnico: scientific-technical/index.md
    - Matemática: scientific-technical/math.md
    - Blocos de código: scientific-technical/code-blocks.md
    - Diagramas Mermaid: scientific-technical/mermaid.md
    - Temporizador Pomodoro: scientific-technical/pomodoro.md
    - Estatísticas de escrita: scientific-technical/writing-statistics.md
  - PKMS/Zettelkasten:
    - PKMS/Zettelkasten: pkms/index.md
    - Métodos de Zettelkasten: pkms/zkn-method.md
    - Visualização de grafo: pkms/graph.md
    - Gerenciador de tags: pkms/tag-manager.md
  - Guias:
    - Guias: guides/index.md
    - Personalizando o Zettlr com CSS: guides/custom-css.md
    - Integração com Zotero: guides/reference-manager-integration.md
    - LanguageTool localmente: guides/languagetool-local.md
    - Apresentações: guides/presentations.md
    - Submetendo a um periódico usando um modelo LaTeX: guides/journal-latex-template.md
    - Aplicativo portátil: guides/portable.md
  - Referência:
    - Referência: reference/index.md
    - Atalhos de teclado: reference/keyboard-shortcuts.md
    - Configurações: reference/settings.md
theme:
  name: readthedocs
  locale: pt
  custom_dir: ../theme_override
  highlightjs: True
  hljs_style: github
  hljs_style_dark: github_dark
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - markdown
    - css
    - yaml
    - latex
    - lua
markdown_extensions:
    - def_list
    - admonition
    - toc:
        permalink: True
plugins:
  - search:
      lang: pt-br
  - git-revision-date-localized
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
