# Builds and deploys the documentation on updates
name: Build

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository (master branch)
      uses: actions/checkout@v6
      with:
        ref: master
        fetch-depth: 0 # Needed for the revisions plugin to work
    - name: Enable Yarn 4.x
      run: corepack enable
    - name: Setup NodeJS ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    # The scripts require some modules that we need to install.
    - name: Install dependencies
      run: yarn install --immutable    
    # Now we can build the thing
    - name: Build the documentation
      run: yarn docs:build

    # Deploy to the server
    - name: Deploy to production
      uses: easingthemes/ssh-deploy@v5.1.0
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-vzhr --delete" # verbose, compress, human-readble, recursive, delete
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
